version: '3.8'
services:
  postgres:
    container_name: GestaoEscola
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12aa12dd
      - POSTGRES_DB=GestaoEscola
